// Code generated by sqlc. DO NOT EDIT.

package objects

import (
	"gopkg.in/guregu/null.v4/zero"
)

type BitburstObject struct {
	OID      int32     `json:"o_id"`
	Online   bool      `json:"online"`
	LastSeen zero.Time `json:"last_seen"`
}
