// Code generated by sqlc. DO NOT EDIT.
// source: objects.sql

package objects

import (
	"context"

	"github.com/lib/pq"
)

const deleteNotSeenObjects = `-- name: DeleteNotSeenObjects :many
DELETE
FROM
	bitburst."objects"
WHERE
	last_seen < CURRENT_TIMESTAMP - INTERVAL '30 seconds' RETURNING o_id
`

func (q *Queries) DeleteNotSeenObjects(ctx context.Context) ([]int32, error) {
	rows, err := q.query(ctx, q.deleteNotSeenObjectsStmt, deleteNotSeenObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var o_id int32
		if err := rows.Scan(&o_id); err != nil {
			return nil, err
		}
		items = append(items, o_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObjectOrUpdate = `-- name: InsertObjectOrUpdate :one
INSERT INTO bitburst."objects" ( o_id )
VALUES
	( $1 ) ON CONFLICT ( o_id ) DO
UPDATE
	SET last_seen = CURRENT_TIMESTAMP,
		online = TRUE
	RETURNING o_id
`

func (q *Queries) InsertObjectOrUpdate(ctx context.Context, oID int32) (int32, error) {
	row := q.queryRow(ctx, q.insertObjectOrUpdateStmt, insertObjectOrUpdate, oID)
	var o_id int32
	err := row.Scan(&o_id)
	return o_id, err
}

const insertObjectsOrUpdate = `-- name: InsertObjectsOrUpdate :many
INSERT INTO bitburst."objects" ( o_id ) 
VALUES ( UNNEST($1::INT[]) ) ON CONFLICT ( o_id ) DO
UPDATE
	SET last_seen = CURRENT_TIMESTAMP,
		online = TRUE
	RETURNING o_id
`

func (q *Queries) InsertObjectsOrUpdate(ctx context.Context, oIds []int32) ([]int32, error) {
	rows, err := q.query(ctx, q.insertObjectsOrUpdateStmt, insertObjectsOrUpdate, pq.Array(oIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var o_id int32
		if err := rows.Scan(&o_id); err != nil {
			return nil, err
		}
		items = append(items, o_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObject = `-- name: UpdateObject :one
UPDATE bitburst."objects"
	SET online = FALSE
	WHERE o_id = $1
	RETURNING o_id
`

func (q *Queries) UpdateObject(ctx context.Context, oID int32) (int32, error) {
	row := q.queryRow(ctx, q.updateObjectStmt, updateObject, oID)
	var o_id int32
	err := row.Scan(&o_id)
	return o_id, err
}
