// Code generated by sqlc. DO NOT EDIT.

package objects

import (
	"context"
)

type Querier interface {
	DeleteNotSeenObjects(ctx context.Context) ([]int32, error)
	InsertObjectsOrUpdate(ctx context.Context, dollar_1 []int32) ([]int32, error)
	UpdateObjects(ctx context.Context, dollar_1 []int32) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
