# this config file serves as an example,
# please create your own config file, prefill it
# and then pass it to program via --config-path flag

log:
  path: "./logs.jsonl"
  level: 1
  beautify: true

server:
  listen_address: "0.0.0.0:9090"
  read_timeout: 0
  write_timeout: 0
  shutdown_timeout: 5s

client:
  tester_service_address: "127.0.0.1:9010"

database:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"
  log_level: 1
  migration_version: 3